stages:
  - build
  - test
  - release
  - deploy

.Build JAR template:
  stage: build
  script:
    - mvn clean install

Build JAR for Java 11:
  image: registry.hpc.ut.ee/mirror/library/maven:3.6-jdk-11
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  extends: .Build JAR template

.Deploy JAR template:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
  script:
    - mvn deploy -Drevision=latest -s ci_settings.xml

Deploy latest JAR for Java 11:
  image: registry.hpc.ut.ee/mirror/library/maven:3.6-jdk-11
  extends: .Deploy JAR template

Release artifact for Java 11:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk update
    - apk add openjdk11 maven jq curl
    - echo $CI_COMMIT_TAG
    - mvn -Drevision=${CI_COMMIT_TAG} clean install
    - |
      RELEASE_DATA="{\"tag_name\": \"$CI_COMMIT_TAG\", \"name\": \"$CI_COMMIT_TAG\"}"
      UPLOAD_URL=$(curl -sH "Authorization: token $GITHUB_JENKINS_TOKEN" -X POST "https://api.github.com/repos/waldur/waldur-keycloak-minio-mapper/releases" -d "$RELEASE_DATA" | jq -r '.upload_url' | cut -d "{" -f 1)
      curl -H "Authorization: token $GITHUB_JENKINS_TOKEN" -H "Content-Type: application/octet-stream" --data-binary "@target/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.jar" "$UPLOAD_URL?name=${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.jar"
  artifacts:
    paths:
      - "target/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.jar"
    expire_in: never
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG_MESSAGE"
    assets:
      links:
        - name: "JAR"
          url: "https://code.opennodecloud.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/download"

Upload docs:
  image:
    name: registry.hpc.ut.ee/mirror/alpine/git:v2.30.2
    entrypoint: [""]
  stage: deploy
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH" && $CI_PIPELINE_SOURCE == "schedule"'
  script:
    - cd /tmp/
    - git clone "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/waldur/waldur-docs.git"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - cd waldur-docs/
    - ls docs/integrations/waldur-keycloak-minio-mapper || mkdir docs/integrations/waldur-keycloak-minio-mapper
    - cp -v $CI_PROJECT_DIR/README.md docs/integrations/waldur-keycloak-minio-mapper
    - git add docs/integrations/waldur-keycloak-minio-mapper
    - git commit -m 'Update Waldur keycloak mapper docs' || exit 0
    - git branch new-keycloak-mapper-docs
    - git push --set-upstream origin new-keycloak-mapper-docs:master
